version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: week_project
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: week_project
      JWT_SECRET: WEE_WOO_MON_AMI
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/app
    command: npm run start:dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: